name: Compile LaTeX Whitepaper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build_latex:
    name: Build PDF Document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload Compiled PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stabolut-Whitepaper-PDF
          path: main.pdf
